repos:

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
    - id: terraform-fmt
      name: Lint Terraform
    - id: terraform-validate
      name: Validate Terraform

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.1.1
  hooks:
    - id: shellcheck

- repo: https://github.com/yelp/detect-secrets.git
  rev: v0.14.3
  hooks:
    - id: detect-secrets
      name: Detect secrets
      args: ['--baseline', '.secrets.baseline']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
